apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patchesStrategicMerge:
  - replicas.yaml
configMapGenerator:
  - name: mykustom-map
    env:
      - name: CONFIG_PROPERTY
        value: "config.properties"
